#! /bin/sh

set -e

. /usr/share/debconf/confmodule

ARCH=`udpkg --print-architecture`

db_get debian-installer/locale
LOCALE="$RET"

# Set locale to C if it has not yet been set
# This can happen during e.g. s390 installs where localechooser is not run
[ -z "$LOCALE" ] && LOCALE="C.UTF-8"

LANGUAGE=${LOCALE%%_*}

# Install specific packages depending on selected language

if [ "$LOCALE" != "C" ] && [ "$LOCALE" != "C.UTF-8" ]; then
	# Other language specific packages
	case "$LANGUAGE" in
	    ar|he|fa)
		# RTL languages (Arabic, Hebrew, Farsi)
		apt-install libfribidi0 || true
		;;
	    ja)
		# japanese		
		apt-install nimf-anthy fonts-takao-pgothic language-pack-gnome-ja-base language-pack-ja-base || true		
		;;
	    zh_CN|zh_TW)
		# chineses		
		apt-install nimf-rime language-pack-gnome-zh-hans language-pack-gnome-zh-hant language-pack-zh-hans language-pack-zh-hant || true		
		;;		
	esac
fi

exit 0
